name:"podcast generator"
author: "Sergio Belda"
description: "Generates a podcast from a given text"
runs:
  using:"docker"
  image: "Dockerfile"
branding:
  icon: "podcast"
  color: "blue"
inputs:
  email:
    description: "Email address to send the podcast to"
    required: true
    default: ${{github.actor}}@localhost
  names:
    description: "Names of the speakers, separated by commas"
    required: true
    default: ${{github.actor}}
